apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: yurigarrido/gitopsfc
  newTag: dbd77cfc7f0d52128defaa879e2975c0ede50e55
