apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  ports:
    - port: 3000        # Porta exposta no Cluster
      targetPort: 3000   # Porta do contêiner
      nodePort: 30080    # Porta externa que ficará disponível no nó
  type: NodePort
